### ISSUE TITLE
Bob doesn't pick up workspaces after remote URL change

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#358] opened 2020-07-15 08:44 UTC
When the remote URLs of repositories change within their recipes, Bob doesn't re-use existing workspaces even when their respecting remote URLs have been manually changed to the new URL before running Bob again. Whilst this may be an edge case, it's definitively an issue when you have a workspace containing many different changed repositories and have to change the remote URL of all of them.

**Comment by jkloetzke** [comment] 2020-07-15 10:22
May be a duplicate of #346. Currently Bob does not look at the workspace but only compares the current SCM state to the last checkout run.

But generally speaking changing the URL of a SCM is like a new checkout. Unless a commit-id specified (I assume you're speaking about a git repository) there could be anything at the new URL. Bob cannot assume that the old and the new URL share a common history. So I'm not sure if that can be implemented safely.

**Comment by Ferruck** [comment] 2020-07-15 10:55
> But generally speaking changing the URL of a SCM is like a new checkout. Unless a commit-id specified (I assume you're speaking about a git repository) there could be anything at the new URL. Bob cannot assume that the old and the new URL share a common history. So I'm not sure if that can be implemented safely.

I agree with you *in general*, that's why I said it's an edge case. In this *specific* case, though, the new URL matches the URL in the recipe (because they've been changed, as well).

**Comment by jkloetzke** [comment] 2020-07-15 11:52
Yes, I do see the point. I've added this special case to #346. In the end it's all about to *not* move something into the attic if the workspace matches the new recipe state.

**Closed by jkloetzke** 2020-07-15 11:52 UTC
Labels: duplicate, enhancement
