### ISSUE TITLE
0.19.1 internal exception

### ISSUE THREAD

**Issue by Desperado17** [BobBuildTool/bob#544] opened 2023-12-15 10:02 UTC
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.19.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/bob/scripts.py", line 147, in catchErrors
    ret = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bob/scripts.py", line 248, in cmd
    ret = cmd(args.args, bobRoot)
  File "/usr/local/lib/python3.10/dist-packages/bob/scripts.py", line 29, in __develop
    doDevelop(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/build.py", line 313, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/build.py", line 263, in commonBuildDevelop
    builder.cook(backlog, True if args.build_mode == 'checkout-only' else False)
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/builder.py", line 828, in cook
    raise self.__buildErrors[0]
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/builder.py", line 722, in __taskWrapper
    ret = await coro()
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/builder.py", line 882, in _cookStep
    await self._cookCheckoutStep(step, depth)
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/builder.py", line 1011, in _cookCheckoutStep
    didSwitch = await self.__runScmSwitch(checkoutStep,
  File "/usr/local/lib/python3.10/dist-packages/bob/cmds/build/builder.py", line 1791, in __runScmSwitch
    ret = await invoker.executeScmSwitch(scm, oldSpec)
  File "/usr/local/lib/python3.10/dist-packages/bob/invoker.py", line 515, in executeScmSwitch
    await scm.switch(self, oldSpec)
  File "/usr/local/lib/python3.10/dist-packages/bob/scm/git.py", line 376, in switch
    await self.invoke(invoker, True)
  File "/usr/local/lib/python3.10/dist-packages/bob/scm/git.py", line 177, in invoke
    await self.__checkoutBranch(invoker, fetchCmd, switch)
  File "/usr/local/lib/python3.10/dist-packages/bob/scm/git.py", line 201, in __checkoutBranch
    assert not self.__submodules
AssertionError

**Comment by jkloetzke** [comment] 2023-12-15 20:57
Duplicate of #440. Fixed since v0.20.0.

I'd strongly recommend to switch to some newer release. 0.19.1 is 2.5 years old by now...

**Closed by jkloetzke** 2023-12-15 20:57 UTC
